BEGIN;

REVOKE ALL PRIVILEGES ON SCHEMA public FROM backend;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM backend;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM backend;

REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM backend;

DROP ROLE IF EXISTS backend;

COMMIT;