BEGIN;

CREATE USER backend 
    WITH ENCRYPTED PASSWORD 'backend' 
    NOCREATEDB 
    NOCREATEROLE 
    NOINHERIT;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO backend;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO backend;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO backend;

COMMIT;